package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"

	"github.com/ubiquiti-community/go-unifi/internal/behavior"
)

// The measured-behaviour artifact (schemas/behavior.json) is a generator
// input like the validators and sensitive_metadata.json already are: the
// probes record what the pinned controller actually does, and the generator
// turns that record into code. A missing artifact means nothing has been
// measured yet, and every consumer here degrades to a no-op -- the same
// posture loadSensitiveMetadata takes for its file.

// applyWriteContract turns one resource's measured write contract into
// generator decisions. A zero contract -- no artifact, or a resource the
// probes have not measured -- changes nothing.
func applyWriteContract(r *ResourceInfo, w behavior.WriteContract) {
	if len(w.RequiredOnCreate) > 0 {
		r.FieldProcessor = withRequiredOnCreate(w.RequiredOnCreate, r.FieldProcessor)
	}
	// Only PUT is a measured deviation the template knows how to emit;
	// POST (or an empty verb) is the default already.
	if w.CreateVerb == "PUT" {
		r.CreateMethod = "PUT"
	}
}

// withRequiredOnCreate drops the omitempty tag from the fields the
// controller was measured to require on create, so their zero values reach
// the wire instead of vanishing from the request.
//
// It wraps outermost and matches on the wire name, because the measurement
// is authoritative: a hand-written processor's omitempty guess retires the
// day the probe records the field as required.
func withRequiredOnCreate(required []string, next func(string, *FieldInfo) error) func(string, *FieldInfo) error {
	names := make(map[string]bool, len(required))
	for _, n := range required {
		names[n] = true
	}
	return func(name string, f *FieldInfo) error {
		if next != nil {
			if err := next(name, f); err != nil {
				return err
			}
		}
		if names[f.JSONName] {
			f.OmitEmpty = false
		}
		return nil
	}
}

// renderCoercionsFile emits the measured coercion floors as consumable Go,
// so a caller can know before writing that the controller will silently
// rewrite a value -- the conntrack timeout floors and their kin. An empty
// artifact still emits the file, with an empty map, so the output set is
// stable whether or not anything has been measured.
func renderCoercionsFile(pkg string, coercions map[string]map[string]behavior.Coercion) ([]byte, error) {
	resources := make([]string, 0, len(coercions))
	for r := range coercions {
		resources = append(resources, r)
	}
	sort.Strings(resources)

	var b bytes.Buffer
	fmt.Fprintf(&b, `// Code generated by go-unifi. DO NOT EDIT.

package %s

// FieldCoercionFloors records, per resource and wire field name, the value
// the controller stored when a probe wrote a below-range value -- measured
// floors and clamps from schemas/behavior.json, not guesses. A field listed
// here is one the controller rewrites in silence: what was written is not
// what a read returns, and nothing in the response says so.
var FieldCoercionFloors = map[string]map[string]string{`, pkg)
	if len(resources) == 0 {
		b.WriteString("}\n")
		return format.Source(b.Bytes())
	}
	b.WriteString("\n")
	for _, r := range resources {
		fields := make([]string, 0, len(coercions[r]))
		for f := range coercions[r] {
			fields = append(fields, f)
		}
		sort.Strings(fields)
		fmt.Fprintf(&b, "\t%q: {\n", r)
		for _, f := range fields {
			fmt.Fprintf(&b, "\t\t%q: %q,\n", f, coercions[r][f].Stored)
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}
