package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
)

// renderSensitiveFile emits the set of wire names the controller itself marks
// sensitive, so the client's error path redacts them by name rather than by
// guessing from substrings.
//
// The substring list it supplements ("password", "secret", "psk", …) covers
// six shapes and misses 51 of the controller's own 64 sensitive fields — every
// OpenVPN key (x_ca_key, x_server_key, x_shared_client_key, x_dh_key), the SSH
// password hashes, the API and SSO tokens, the SIM PIN, and the PII. It also
// misses by a single character: the list has "pre_shared_key" and the wire
// name is "wireguard_client_preshared_key".
//
// Guessing from names is one field away from wrong in a way nothing detects,
// and the controller already publishes the answer in
// schemas/metadata/sensitive_metadata.json.
func renderSensitiveFile(pkg string, sensitive sensitiveIndex) ([]byte, error) {
	// Filtered to secret material by the same rule the specification uses.
	// sensitive_metadata.json also carries anonymization-only entries -- name,
	// desc, hostname, serial, usernames, certificates -- and redacting those
	// from an error would remove exactly what makes it diagnosable, for no
	// secrecy gain.
	byCollection := map[string][]string{}
	names := map[string]bool{}
	for collection, fields := range sensitive {
		for name := range fields {
			if !secretNameRe.MatchString(name) {
				continue
			}
			names[name] = true
			byCollection[collection] = append(byCollection[collection], name)
		}
	}
	sorted := make([]string, 0, len(names))
	for n := range names {
		sorted = append(sorted, n)
	}
	sort.Strings(sorted)
	collections := make([]string, 0, len(byCollection))
	for c := range byCollection {
		sort.Strings(byCollection[c])
		collections = append(collections, c)
	}
	sort.Strings(collections)

	var b bytes.Buffer
	fmt.Fprintf(&b, `// Code generated by go-unifi. DO NOT EDIT.

package %s

// sensitiveWireFields are the field names the controller's own
// sensitive_metadata.json marks sensitive, flattened across collections.
//
// The client redacts these from the request body it attaches to a non-2xx
// error. They are matched exactly and case-insensitively, which is what makes
// this different from the substring list beside it: a substring list is one
// unanticipated field name away from printing key material, and cannot be
// audited against anything.
//
// %d names.
var sensitiveWireFields = map[string]bool{
`, pkg, len(sorted))
	for _, n := range sorted {
		fmt.Fprintf(&b, "\t%q: true,\n", n)
	}
	b.WriteString("}\n")

	// The structured form, for consumers. The flat set above is its union and
	// exists for the redactor's exact-name lookup; both come from the same
	// pass so they cannot disagree.
	fmt.Fprintf(&b, `
// SensitiveFieldsByCollection is the controller's own declaration of which
// fields carry secret material, from sensitive_metadata.json, filtered to
// actual secrets by the same rule that sets Sensitive in the generated
// Terraform specification. Anonymization-only entries (name, hostname,
// serial, ...) are deliberately absent.
//
// Keys are the controller's collection names -- the lowercased schema file
// base names such as "networkconf" or "setting" -- not Go type names. Values
// are leaf wire names: a nested declaration like "auth_servers.x_secret" is
// recorded as "x_secret", because that is the key a consumer sees on the
// object it holds.
//
// Derive from this rather than hand-maintaining a list: a hand-set list is
// one unanticipated field name away from wrong, and nothing detects the day
// that happens.
var SensitiveFieldsByCollection = map[string][]string{
`)
	for _, c := range collections {
		fmt.Fprintf(&b, "\t%q: {\n", c)
		for _, n := range byCollection[c] {
			fmt.Fprintf(&b, "\t\t%q,\n", n)
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")

	// The same rule the specification generator uses to tell secret material
	// from anonymization-only entries, emitted so the client and the
	// generator cannot drift into two different definitions of "secret".
	// It is the fallback for names the controller does not enumerate --
	// wireguard_client_preshared_key is one underscore away from the old
	// hand-written "pre_shared_key" and was printing in full.
	fmt.Fprintf(&b, "\n// sensitiveNamePattern is %s, shared with the generator.\nvar sensitiveNamePattern = regexp.MustCompile(%q)\n",
		"the generator's secret-name rule", secretNameRe.String())
	src := bytes.Replace(b.Bytes(), []byte("package "+pkg+"\n"), []byte("package "+pkg+"\n\nimport \"regexp\"\n"), 1)
	return format.Source(src)
}
