// Code generated by go-unifi. DO NOT EDIT.

package unifi

// FieldCoercionFloors records, per resource and wire field name, the value
// the controller stored when a probe wrote a below-range value -- measured
// floors and clamps from schemas/behavior.json, not guesses. A field listed
// here is one the controller rewrites in silence: what was written is not
// what a read returns, and nothing in the response says so.
var FieldCoercionFloors = map[string]map[string]string{
	"SettingUsg": {},
}
