// Code generated by go-unifi. DO NOT EDIT.

package unifi

import "regexp"

// sensitiveWireFields are the field names the controller's own
// sensitive_metadata.json marks sensitive, flattened across collections.
//
// The client redacts these from the request body it attaches to a non-2xx
// error. They are matched exactly and case-insensitively, which is what makes
// this different from the substring list beside it: a substring list is one
// unanticipated field name away from printing key material, and cannot be
// audited against anything.
//
// 28 names.
var sensitiveWireFields = map[string]bool{
	"lte_password":            true,
	"lte_sim_pin":             true,
	"secret_verifier_encoded": true,
	"x_api_token":             true,
	"x_auth_key":              true,
	"x_authkey":               true,
	"x_baresip_password":      true,
	"x_ble_adopt_key":         true,
	"x_ble_auth_key":          true,
	"x_ca_key":                true,
	"x_dh_key":                true,
	"x_ipsec_pre_shared_key":  true,
	"x_mesh_psk":              true,
	"x_mgmt_key":              true,
	"x_openvpn_password":      true,
	"x_passphrase":            true,
	"x_password":              true,
	"x_private_key":           true,
	"x_secret":                true,
	"x_server_key":            true,
	"x_shared_client_key":     true,
	"x_ssh_md5passwd":         true,
	"x_ssh_password":          true,
	"x_ssh_sha512passwd":      true,
	"x_sso_token":             true,
	"x_stunnel_key":           true,
	"x_wan_password":          true,
	"x_wireguard_private_key": true,
}

// sensitiveNamePattern is the generator's secret-name rule, shared with the generator.
var sensitiveNamePattern = regexp.MustCompile("(?i)passw|passphrase|secret|token|psk|sim_pin|private_key|auth_?key|_key$")
