//go:build integration

package unifi

import (
	"context"
	"os"
	"reflect"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/ubiquiti-community/go-unifi/internal/controllertest"
)

// v1DriftAllowlist names wire fields a live controller returns that the
// generated structs do not model, with the reason each is tolerated.
//
// Every entry was measured on 10.6.101. A field arriving here is not
// automatically a defect -- the controller assigns some of these itself and
// never accepts them on a write -- but it is always a decision, which is
// what this list records.
var v1DriftAllowlist = map[string]string{
	// Assigned by the controller on several v1 collections and on the v2
	// firewall zone. Never sent by a caller; modelling it would add a field
	// nothing can set.
	"external_id": "controller-assigned identifier, read-only",

	// WLAN only. The controller's own short handle for the SSID.
	"short_id": "controller-assigned WLAN handle, read-only",

	// WLAN only. Records whether the controller generated the passphrase
	// rather than the caller choosing it.
	"passphrase_autogenerated": "controller-reported status of x_passphrase",

	// Device (stat/device). Measured on 10.6.101 with an adopted emulated
	// UXGENT (unifi-emu-herder 0.5.3): the controller returns every field
	// below, and none of them appear in its own published Device.json --
	// verified against the extracted definitions the capture lock pins
	// (positive controls: hostname, name, poe_mode, port_overrides and
	// mgmt_network_id all resolve in the same file). So none are generator
	// gaps: the definitions describe the writable configuration, and
	// stat/device layers the controller's entire runtime view on top,
	// undeclared. Recorded here, deliberately not modelled -- a field the
	// controller's definitions lack is a finding, not an SDK field.
	//
	// last_config_applied_successfully -- the field this probe exists for --
	// is deliberately NOT listed. A freshly adopted UXGENT does not emit it
	// (measured twice, 45s apart), though it was seen present-and-false on
	// the same controller generation after provisioning activity
	// (2026-08-30). The day it shows up here, the probe goes red and names
	// it, which is the watch working.

	// Adoption bookkeeping the controller stamps as a device informs its
	// way in.
	"adopt_ip":                   "adoption bookkeeping, controller-stamped",
	"adopt_manual":               "adoption bookkeeping, controller-stamped",
	"adopt_state":                "adoption bookkeeping, controller-stamped",
	"adopt_status":               "adoption bookkeeping, controller-stamped",
	"adopt_tries":                "adoption bookkeeping, controller-stamped",
	"adopt_url":                  "adoption bookkeeping, controller-stamped",
	"adoptable_when_upgraded":    "adoption bookkeeping, controller-stamped",
	"adopted_at":                 "adoption bookkeeping, controller-stamped",
	"adoption_completed":         "adoption bookkeeping, controller-stamped",
	"default":                    "adoption bookkeeping, controller-stamped",
	"discovered_via":             "adoption bookkeeping, controller-stamped",
	"inform_discovery_source_ip": "adoption bookkeeping, controller-stamped",
	"inform_url":                 "adoption bookkeeping, controller-stamped",
	"locating":                   "adoption bookkeeping, controller-stamped",

	// Provisioning bookkeeping: the controller's own record of which
	// configuration generation it pushed and when.
	"cfgversion":       "provisioning bookkeeping, controller-stamped",
	"known_cfgversion": "provisioning bookkeeping, controller-stamped",
	"provisioned_at":   "provisioning bookkeeping, controller-stamped",

	// Firmware upgrade pipeline. upgrade_state and upgrade_to_firmware are
	// two phases of the same async catalog check -- see
	// v1DriftPhaseDependent.
	"reboot_duration":      "firmware/upgrade pipeline state",
	"rollupgrade":          "firmware/upgrade pipeline state",
	"safe_for_autoupgrade": "firmware/upgrade pipeline state",
	"upgradable":           "firmware/upgrade pipeline state",
	"upgrade_duration":     "firmware/upgrade pipeline state",
	"upgrade_state":        "firmware/upgrade pipeline state",
	"upgrade_to_firmware":  "firmware/upgrade pipeline state",

	// Runtime telemetry: counters, timestamps and stats objects that move
	// between reads (uptime, last_seen, stat and system-stats measured
	// changing across a 45s window).
	"_uptime":                   "runtime telemetry, read-only",
	"bytes":                     "runtime telemetry, read-only",
	"connected_at":              "runtime telemetry, read-only",
	"guest-lan-num_sta":         "runtime telemetry, read-only",
	"guest-num_sta":             "runtime telemetry, read-only",
	"guest-wlan-num_sta":        "runtime telemetry, read-only",
	"lan-num_sta":               "runtime telemetry, read-only",
	"last_downtime_stats":       "runtime telemetry, read-only",
	"last_seen":                 "runtime telemetry, read-only",
	"next_interval":             "runtime telemetry, read-only",
	"num_desktop":               "runtime telemetry, read-only",
	"num_handheld":              "runtime telemetry, read-only",
	"num_mobile":                "runtime telemetry, read-only",
	"num_sta":                   "runtime telemetry, read-only",
	"rx_bytes":                  "runtime telemetry, read-only",
	"start_connected_millis":    "runtime telemetry, read-only",
	"start_disconnected_millis": "runtime telemetry, read-only",
	"startup_timestamp":         "runtime telemetry, read-only",
	"stat":                      "runtime telemetry, read-only",
	"sys_stats":                 "runtime telemetry, read-only",
	"system-stats":              "runtime telemetry, read-only",
	"tx_bytes":                  "runtime telemetry, read-only",
	"uptime":                    "runtime telemetry, read-only",
	"uptime_stats":              "runtime telemetry, read-only",
	"user-lan-num_sta":          "runtime telemetry, read-only",
	"user-num_sta":              "runtime telemetry, read-only",
	"user-wlan-num_sta":         "runtime telemetry, read-only",
	"wlan-num_sta":              "runtime telemetry, read-only",

	// Hardware identity and description, reported by the device or derived
	// from the controller's model catalog.
	"device_id":           "hardware identity, device-reported",
	"displayable_version": "hardware identity, device-reported",
	"has_eth1":            "hardware identity, device-reported",
	"has_fan":             "hardware identity, device-reported",
	"has_speaker":         "hardware identity, device-reported",
	"has_temperature":     "hardware identity, device-reported",
	"is_access_point":     "hardware identity, device-reported",
	"model_in_eol":        "hardware identity, model-catalog derived",
	"model_in_lts":        "hardware identity, model-catalog derived",
	"model_incompatible":  "hardware identity, model-catalog derived",
	"overheating":         "hardware identity, device-reported",
	"serial":              "hardware identity, device-reported",
	"setup_id":            "hardware identity, controller-assigned",
	"shortname":           "hardware identity, model-catalog derived",
	"support_wifi6e":      "hardware identity, device-reported",
	"sysid":               "hardware identity, device-reported",
	"unsupported":         "hardware identity, model-catalog derived",
	"unsupported_reason":  "hardware identity, model-catalog derived",
	"version":             "hardware identity, device-reported",

	// Capability bitmasks the device reports at inform; the controller
	// gates features on them (e.g. udapi_caps bit 22 gates BGP).
	"credential_caps": "capability bitmask, device-reported",
	"fw2_caps":        "capability bitmask, device-reported",
	"fw3_caps":        "capability bitmask, device-reported",
	"fw_caps":         "capability bitmask, device-reported",
	"hw_caps":         "capability bitmask, device-reported",
	"switch_caps":     "capability bitmask, device-reported",
	"udapi_caps":      "capability bitmask, device-reported",
	"udapi_version":   "capability descriptor, device-reported",
	"usg2_caps":       "capability bitmask, device-reported",
	"usg_caps":        "capability bitmask, device-reported",
	"wifi_caps":       "capability bitmask, device-reported",
	"wifi_caps2":      "capability bitmask, device-reported",

	// Topology and network reports assembled by the controller from what
	// the device sees around itself.
	"active_geo_info":              "topology/network report, read-only",
	"connection_network_id":        "topology/network report, read-only",
	"connection_network_name":      "topology/network report, read-only",
	"downlink_table":               "topology/network report, read-only",
	"ethernet_table":               "topology/network report, read-only",
	"geo_info":                     "topology/network report, read-only",
	"last_connection_network_id":   "topology/network report, read-only",
	"last_connection_network_name": "topology/network report, read-only",
	"last_geo_info":                "topology/network report, read-only",
	"link_aggregation_groups":      "topology/network report, read-only",
	"lldp_table":                   "topology/network report, read-only",
	"network_table":                "topology/network report, read-only",
	"reported_networks":            "topology/network report, read-only",
	"ruleset_interfaces":           "topology/network report, read-only",

	// Inform-plane credentials and key material. Never model these.
	"syslog_key":        "inform credentials, controller-held secret",
	"x_aes_gcm":         "inform credentials, controller-held secret",
	"x_authkey":         "inform credentials, controller-held secret",
	"x_has_ssh_hostkey": "inform credentials, controller-held secret",
}

// v1DriftPhaseDependent marks allowlisted fields whose presence depends on
// where an async controller job stands when the probe reads. The firmware
// catalog check swaps upgrade_state for upgrade_to_firmware once it
// completes (measured: both shapes within 45s of adoption on 10.6.101), so
// a single read legitimately sees one and not the other. The staleness
// sweep skips these; every other entry must show up on every full run.
var v1DriftPhaseDependent = map[string]bool{
	"upgrade_state":       true,
	"upgrade_to_firmware": true,
}

// v1DriftProbes are the collections compared, with a seed where the site
// ships none of that object. A seed returning a body has it POSTed to the
// collection; a nil return means the seed provisioned some other way -- a
// device cannot be created over REST, only run and adopted.
var v1DriftProbes = []struct {
	label string
	path  string
	model any
	seed  func(ctx context.Context, t *testing.T, c *controllertest.Controller, s *controllertest.Session) map[string]any
}{
	{label: "networkconf", path: "/rest/networkconf", model: &Network{}},
	{label: "portconf", path: "/rest/portconf", model: &PortProfile{},
		seed: func(context.Context, *testing.T, *controllertest.Controller, *controllertest.Session) map[string]any {
			return map[string]any{"name": "drift-probe", "forward": "all", "autoneg": true}
		}},
	{label: "firewallgroup", path: "/rest/firewallgroup", model: &FirewallGroup{},
		seed: func(context.Context, *testing.T, *controllertest.Controller, *controllertest.Session) map[string]any {
			return map[string]any{"name": "drift-probe", "group_type": "address-group",
				"group_members": []string{"10.0.0.1"}}
		}},
	{label: "wlanconf", path: "/rest/wlanconf", model: &WLAN{},
		seed: func(ctx context.Context, t *testing.T, c *controllertest.Controller, s *controllertest.Session) map[string]any {
			return map[string]any{
				"name": "drift-probe", "enabled": true, "security": "wpapsk",
				"x_passphrase": "probe-passphrase", "wpa_mode": "wpa2", "wpa_enc": "ccmp",
				"usergroup_id": firstObjectID(ctx, t, s, c.Site, "usergroup"),
				"wlangroup_id": firstObjectID(ctx, t, s, c.Site, "wlangroup"),
				"ap_group_ids": []string{requiredAPGroupID(ctx, t, s, c.Site)},
			}
		}},
	// stat/device, not /rest: devices are the one collection whose documents
	// only exist because a device informed its way in, so the seed adopts an
	// emulated gateway instead of POSTing. AdoptGateway skips the subtest on
	// targets that cannot herd devices (UOS, no herder binary); the allowlist
	// sweep below stays quiet then, because a skipped probe cannot vouch for
	// its entries.
	{label: "device", path: "/stat/device", model: &Device{},
		seed: func(ctx context.Context, t *testing.T, c *controllertest.Controller, s *controllertest.Session) map[string]any {
			controllertest.AdoptGateway(ctx, t, c, s)
			return nil
		}},
}

// TestIntegrationV1Drift compares what a live controller returns for the v1
// collections against what the generated structs model.
//
// The v1 definitions come from the controller's own schema files, which is a
// far better source than the hand-written v2 ones -- but it had never been
// checked on the read side. A field the controller stores and returns while
// its published schema stays silent is invisible to every consumer of this
// client, and nothing would have said so.
//
// It is not symmetric with the v2 probe on purpose. A schema field missing
// from the wire is ordinary: an option nobody set is simply absent. A wire
// field missing from the schema is the discovery.
func TestIntegrationV1Drift(t *testing.T) {
	if os.Getenv("UNIFI_TEST_URL") != "" {
		t.Skip("mutating probe only runs against the disposable container")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Minute)
	defer cancel()
	c := controllertest.StartForHarness(ctx, t)
	s := c.NewSession(ctx, t)

	seen := map[string]bool{}
	compared := 0
	for _, probe := range v1DriftProbes {
		t.Run(probe.label, func(t *testing.T) {
			defer func() {
				if !t.Skipped() {
					compared++
				}
			}()
			path := "/api/s/" + c.Site + probe.path
			if probe.seed != nil {
				if seed := probe.seed(ctx, t, c, s); seed != nil {
					body, status, err := s.PostJSON(ctx, path, seed)
					if err != nil || status != 200 {
						t.Fatalf("seeding %s failed (HTTP %d): %v %v", probe.label, status, body, err)
					}
					if id, _ := firstData(t, body)["_id"].(string); id != "" {
						defer s.DeleteJSON(ctx, path+"/"+id) //nolint:errcheck
					}
				}
			}

			body, status, err := s.GetJSON(ctx, path)
			if err != nil || status != 200 {
				t.Fatalf("listing %s failed (HTTP %d): %v", probe.label, status, err)
			}
			m, _ := body.(map[string]any)
			data, _ := m["data"].([]any)
			if len(data) == 0 {
				t.Fatalf("%s has no stored objects, so this run compares nothing", probe.label)
			}

			modelled := declaredWireNames(probe.model)
			live := map[string]bool{}
			for _, entry := range data {
				d, _ := entry.(map[string]any)
				for wire := range d {
					live[wire] = true
				}
			}

			var undeclared []string
			for wire := range live {
				if modelled[wire] {
					continue
				}
				seen[wire] = true
				if _, allowed := v1DriftAllowlist[wire]; allowed {
					continue
				}
				undeclared = append(undeclared, wire)
			}
			sort.Strings(undeclared)

			if len(undeclared) > 0 {
				t.Errorf("the controller returns %d field(s) on %s that no generated struct models:\n  %s\n\n"+
					"The schema files this client generates from do not mention them, so nothing "+
					"downstream can read them. Decide what each one is -- controller-assigned and "+
					"read-only, or a real option worth carrying -- and either add it through "+
					"overrides/fields.toml with the measurement recorded, or list it in "+
					"v1DriftAllowlist with the reason.",
					len(undeclared), probe.label, strings.Join(undeclared, "\n  "))
			}
		})
	}

	// A stale allowlist hides the next one, so entries that no longer drift
	// have to come off -- but only when every probe ran: a skipped probe (the
	// device one, on a target that cannot herd devices) leaves its entries
	// legitimately unseen.
	if compared == len(v1DriftProbes) {
		for wire := range v1DriftAllowlist {
			if !seen[wire] && !v1DriftPhaseDependent[wire] {
				t.Errorf("v1DriftAllowlist carries %q, but no probed collection returns it unmodelled any more; "+
					"take it off the list", wire)
			}
		}
	}
}

// declaredWireNames returns the wire names a generated type declares,
// walking embedded structs so the shared envelope counts as modelled.
func declaredWireNames(v any) map[string]bool {
	out := map[string]bool{}
	typ := reflect.TypeOf(v)
	for typ != nil && typ.Kind() == reflect.Pointer {
		typ = typ.Elem()
	}
	if typ == nil || typ.Kind() != reflect.Struct {
		return out
	}

	var walk func(reflect.Type)
	walk = func(t reflect.Type) {
		for i := range t.NumField() {
			field := t.Field(i)
			if field.Anonymous {
				embedded := field.Type
				for embedded.Kind() == reflect.Pointer {
					embedded = embedded.Elem()
				}
				if embedded.Kind() == reflect.Struct {
					walk(embedded)
				}
				continue
			}
			name, _, _ := strings.Cut(field.Tag.Get("json"), ",")
			if name != "" && name != "-" {
				out[name] = true
			}
		}
	}
	walk(typ)
	return out
}
