//go:build integration

package unifi

import (
	"context"
	"os"
	"reflect"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/ubiquiti-community/go-unifi/internal/controllertest"
)

// v1DriftAllowlist names wire fields a live controller returns that the
// generated structs do not model, with the reason each is tolerated.
//
// Every entry was measured on 10.6.101. A field arriving here is not
// automatically a defect -- the controller assigns some of these itself and
// never accepts them on a write -- but it is always a decision, which is
// what this list records.
var v1DriftAllowlist = map[string]string{
	// Assigned by the controller on several v1 collections and on the v2
	// firewall zone. Never sent by a caller; modelling it would add a field
	// nothing can set.
	"external_id": "controller-assigned identifier, read-only",

	// WLAN only. The controller's own short handle for the SSID.
	"short_id": "controller-assigned WLAN handle, read-only",

	// WLAN only. Records whether the controller generated the passphrase
	// rather than the caller choosing it.
	"passphrase_autogenerated": "controller-reported status of x_passphrase",
}

// v1DriftProbes are the collections compared, with a seed where the site
// ships none of that object.
var v1DriftProbes = []struct {
	label string
	path  string
	model any
	seed  func(ctx context.Context, t *testing.T, s *controllertest.Session, site string) map[string]any
}{
	{label: "networkconf", path: "/rest/networkconf", model: &Network{}},
	{label: "portconf", path: "/rest/portconf", model: &PortProfile{},
		seed: func(context.Context, *testing.T, *controllertest.Session, string) map[string]any {
			return map[string]any{"name": "drift-probe", "forward": "all", "autoneg": true}
		}},
	{label: "firewallgroup", path: "/rest/firewallgroup", model: &FirewallGroup{},
		seed: func(context.Context, *testing.T, *controllertest.Session, string) map[string]any {
			return map[string]any{"name": "drift-probe", "group_type": "address-group",
				"group_members": []string{"10.0.0.1"}}
		}},
	{label: "wlanconf", path: "/rest/wlanconf", model: &WLAN{},
		seed: func(ctx context.Context, t *testing.T, s *controllertest.Session, site string) map[string]any {
			return map[string]any{
				"name": "drift-probe", "enabled": true, "security": "wpapsk",
				"x_passphrase": "probe-passphrase", "wpa_mode": "wpa2", "wpa_enc": "ccmp",
				"usergroup_id": firstUserGroupID(ctx, t, s, site),
				"wlangroup_id": firstWLANGroupID(ctx, t, s, site),
				"ap_group_ids": []string{requiredAPGroupID(ctx, t, s, site)},
			}
		}},
}

// TestIntegrationV1Drift compares what a live controller returns for the v1
// collections against what the generated structs model.
//
// The v1 definitions come from the controller's own schema files, which is a
// far better source than the hand-written v2 ones -- but it had never been
// checked on the read side. A field the controller stores and returns while
// its published schema stays silent is invisible to every consumer of this
// client, and nothing would have said so.
//
// It is not symmetric with the v2 probe on purpose. A schema field missing
// from the wire is ordinary: an option nobody set is simply absent. A wire
// field missing from the schema is the discovery.
func TestIntegrationV1Drift(t *testing.T) {
	if os.Getenv("UNIFI_TEST_URL") != "" {
		t.Skip("mutating probe only runs against the disposable container")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Minute)
	defer cancel()
	c := controllertest.StartForHarness(ctx, t)
	s := c.NewSession(ctx, t)

	seen := map[string]bool{}
	for _, probe := range v1DriftProbes {
		t.Run(probe.label, func(t *testing.T) {
			path := "/api/s/" + c.Site + probe.path
			if probe.seed != nil {
				body, status, err := s.PostJSON(ctx, path, probe.seed(ctx, t, s, c.Site))
				if err != nil || status != 200 {
					t.Fatalf("seeding %s failed (HTTP %d): %v %v", probe.label, status, body, err)
				}
				if id, _ := firstData(t, body)["_id"].(string); id != "" {
					defer s.DeleteJSON(ctx, path+"/"+id) //nolint:errcheck
				}
			}

			body, status, err := s.GetJSON(ctx, path)
			if err != nil || status != 200 {
				t.Fatalf("listing %s failed (HTTP %d): %v", probe.label, status, err)
			}
			m, _ := body.(map[string]any)
			data, _ := m["data"].([]any)
			if len(data) == 0 {
				t.Fatalf("%s has no stored objects, so this run compares nothing", probe.label)
			}

			modelled := declaredWireNames(probe.model)
			live := map[string]bool{}
			for _, entry := range data {
				d, _ := entry.(map[string]any)
				for wire := range d {
					live[wire] = true
				}
			}

			var undeclared []string
			for wire := range live {
				if modelled[wire] {
					continue
				}
				seen[wire] = true
				if _, allowed := v1DriftAllowlist[wire]; allowed {
					continue
				}
				undeclared = append(undeclared, wire)
			}
			sort.Strings(undeclared)

			if len(undeclared) > 0 {
				t.Errorf("the controller returns %d field(s) on %s that no generated struct models:\n  %s\n\n"+
					"The schema files this client generates from do not mention them, so nothing "+
					"downstream can read them. Decide what each one is -- controller-assigned and "+
					"read-only, or a real option worth carrying -- and either add it through "+
					"overrides/fields.toml with the measurement recorded, or list it in "+
					"v1DriftAllowlist with the reason.",
					len(undeclared), probe.label, strings.Join(undeclared, "\n  "))
			}
		})
	}

	// A stale allowlist hides the next one, so entries that no longer drift
	// have to come off.
	for wire := range v1DriftAllowlist {
		if !seen[wire] {
			t.Errorf("v1DriftAllowlist carries %q, but no probed collection returns it unmodelled any more; "+
				"take it off the list", wire)
		}
	}
}

// declaredWireNames returns the wire names a generated type declares,
// walking embedded structs so the shared envelope counts as modelled.
func declaredWireNames(v any) map[string]bool {
	out := map[string]bool{}
	typ := reflect.TypeOf(v)
	for typ != nil && typ.Kind() == reflect.Pointer {
		typ = typ.Elem()
	}
	if typ == nil || typ.Kind() != reflect.Struct {
		return out
	}

	var walk func(reflect.Type)
	walk = func(t reflect.Type) {
		for i := range t.NumField() {
			field := t.Field(i)
			if field.Anonymous {
				embedded := field.Type
				for embedded.Kind() == reflect.Pointer {
					embedded = embedded.Elem()
				}
				if embedded.Kind() == reflect.Struct {
					walk(embedded)
				}
				continue
			}
			name, _, _ := strings.Cut(field.Tag.Get("json"), ",")
			if name != "" && name != "-" {
				out[name] = true
			}
		}
	}
	walk(typ)
	return out
}
