// Package rebuild reduces the complete generated-output surface to one digest.
package rebuild

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ubiquiti-community/go-unifi/internal/capturelock"
)

var requiredOutputs = []string{
	"schemas/ARTIFACT",
	"schemas/SOURCE",
	"schemas/VERSION",
	"schemas/capture.lock.json",
	"specification.json",
}

// OutputDigest hashes every file generation produces under root: the
// provenance projections, the lock, specification.json, and the generated Go.
// Each file contributes its tree-relative path, its size and its own digest,
// so a rename or a truncation moves the result as surely as an edit does.
func OutputDigest(root string) (string, error) {
	names := append([]string(nil), requiredOutputs...)
	unifiRoot := filepath.Join(root, "unifi")
	err := filepath.WalkDir(unifiRoot, func(filename string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		// _string.go files are stringer output: generated by the same
		// go generate pass, so their drift must fail the comparison too.
		if entry.IsDir() ||
			(!strings.HasSuffix(entry.Name(), ".generated.go") && !strings.HasSuffix(entry.Name(), "_string.go")) {
			return nil
		}
		if !entry.Type().IsRegular() {
			return fmt.Errorf("generated output %s is not a regular file", filename)
		}
		rel, err := filepath.Rel(root, filename)
		if err != nil {
			return err
		}
		names = append(names, filepath.ToSlash(rel))
		return nil
	})
	if err != nil {
		return "", fmt.Errorf("scan generated Go: %w", err)
	}
	if len(names) == len(requiredOutputs) {
		return "", errors.New("no generated Go outputs found")
	}
	sort.Strings(names)

	outputDigest := sha256.New()
	for _, name := range names {
		filename := filepath.Join(root, filepath.FromSlash(name))
		stat, err := os.Stat(filename)
		if err != nil {
			return "", fmt.Errorf("required rebuild output %s: %w", name, err)
		}
		if !stat.Mode().IsRegular() {
			return "", fmt.Errorf("required rebuild output %s is not a regular file", name)
		}
		digest, err := capturelock.DigestFile(filename)
		if err != nil {
			return "", fmt.Errorf("digest rebuild output %s: %w", name, err)
		}
		fmt.Fprintf(outputDigest, "%s\x00%d\x00%s\x00", name, stat.Size(), digest)
	}
	return hex.EncodeToString(outputDigest.Sum(nil)), nil
}
